### ISSUE TITLE
KVM live migration fails

### ISSUE THREAD

**Issue by giovanni-rigazzi** [atolab/fog05#11]
KVM live migration between two Ubuntu 16.04 machines does not succeed. 
An exception is thrown (see log below)

More details:
- KVM defined, configured and run on the source node
- KVM only defined on the destination node

Source node log:

[2018-05-08 17:56:11,409] - [INFO] > < before_migrate_entity_actions() >  KVM Plugin - Before Migration Source: Waiting destination to be ready
< before_migrate_entity_actions() >  KVM Plugin - Before Migration Source: Waiting destination to be ready
[2018-05-08 17:56:11,453] - [INFO] > < before_migrate_entity_actions() >  KVM Plugin - Before Migration Source: Waiting destination to be ready
< before_migrate_entity_actions() >  KVM Plugin - Before Migration Source: Waiting destination to be ready
...

Destination node log:

[2018-05-08 17:43:56,033] - [INFO] > < __react_to_cache_entity() > KVM Plugin - React to to URI: dfos://0/e22885ddcc59479d932a5478f6c8605d/runtime/8fb33188-846c-45f8-83df-2a25e6b78049/entity/9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e/instance/79ab0ab4-b945-4c63-9682-93f6b69cfe37 Value: {"uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "type": "kvm", "dst": "e22885ddcc59479d932a5478f6c8605d", "status": "landing", "version": 1, "name": "OAI-EPC-test-qcow2-kvm0", "entity_data": {"uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "base_image": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "networks": [{"br_name": "br1", "mac": "d2:e3:ed:6f:e3:ef"}], "name": "OAI-EPC-test-qcow2-kvm", "flavor_id": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "user-data": "", "ssh-key": ""}} Version: 0
< __react_to_cache_entity() > KVM Plugin - React to to URI: dfos://0/e22885ddcc59479d932a5478f6c8605d/runtime/8fb33188-846c-45f8-83df-2a25e6b78049/entity/9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e/instance/79ab0ab4-b945-4c63-9682-93f6b69cfe37 Value: {"uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "type": "kvm", "dst": "e22885ddcc59479d932a5478f6c8605d", "status": "landing", "version": 1, "name": "OAI-EPC-test-qcow2-kvm0", "entity_data": {"uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "base_image": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "networks": [{"br_name": "br1", "mac": "d2:e3:ed:6f:e3:ef"}], "name": "OAI-EPC-test-qcow2-kvm", "flavor_id": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e", "user-data": "", "ssh-key": ""}} Version: 0
[2018-05-08 17:43:56,034] - [WARNING] > < __react_to_cache_entity() > ACTION = landing on separate thread!!
< __react_to_cache_entity() > ACTION = landing on separate thread!!
[2018-05-08 17:43:56,035] - [INFO] > < migrate_entity() >  KVM Plugin - Migrate a VM uuid 9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e
< migrate_entity() >  KVM Plugin - Migrate a VM uuid 9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e
[2018-05-08 17:43:56,043] - [INFO] > < __react_to_cache_flavor() > KVM Plugin - React to to URI: dfos://0/e22885ddcc59479d932a5478f6c8605d/runtime/8fb33188-846c-45f8-83df-2a25e6b78049/flavor/9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e Value: {"cpu": 1, "disk_size": 8, "memory": 2048, "name": "OAI-EPC-test-qcow2-kvm_flavor", "uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e"} Version: 0
< __react_to_cache_flavor() > KVM Plugin - React to to URI: dfos://0/e22885ddcc59479d932a5478f6c8605d/runtime/8fb33188-846c-45f8-83df-2a25e6b78049/flavor/9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e Value: {"cpu": 1, "disk_size": 8, "memory": 2048, "name": "OAI-EPC-test-qcow2-kvm_flavor", "uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e"} Version: 0
[2018-05-08 17:43:56,049] - [INFO] > < __react_to_cache_image() > KVM Plugin - React to to URI: dfos://0/e22885ddcc59479d932a5478f6c8605d/runtime/8fb33188-846c-45f8-83df-2a25e6b78049/image/9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e Value: {"base_image": "localhost:8000/OAI-EPC-DroneSim.qcow2", "path": "/opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2", "format": "qcow2", "name": "OAI-EPC-test-qcow2-kvm_img", "uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e"} Version: 0
< __react_to_cache_image() > KVM Plugin - React to to URI: dfos://0/e22885ddcc59479d932a5478f6c8605d/runtime/8fb33188-846c-45f8-83df-2a25e6b78049/image/9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e Value: {"base_image": "localhost:8000/OAI-EPC-DroneSim.qcow2", "path": "/opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2", "format": "qcow2", "name": "OAI-EPC-test-qcow2-kvm_img", "uuid": "9fa75e6a-d9c3-11e7-b769-5f3db30f0c2e"} Version: 0
[2018-05-08 17:43:56,049] - [INFO] > < executeCommand() > OS Plugin executing command wget localhost:8000/OAI-EPC-DroneSim.qcow2 -O /opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2
< executeCommand() > OS Plugin executing command wget localhost:8000/OAI-EPC-DroneSim.qcow2 -O /opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/giovanni/src/fog05/plugins/KVMLibvirt/KVMLibvirt_plugin.py", line 605, in migrate_entity
    if instance.get_state() not in [State.RUNNING, State.TAKING_OFF]:
AttributeError: 'NoneType' object has no attribute 'get_state'

--2018-05-08 17:43:56--  http://localhost:8000/OAI-EPC-DroneSim.qcow2
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7425687552 (6.9G) [application/octet-stream]
Saving to: ‘/opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2’

/opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2                100%[===================================================================================================================================>]   6.92G  79.9MB/s    in 82s     

2018-05-08 17:45:18 (86.3 MB/s) - ‘/opt/fos/kvm/images/OAI-EPC-DroneSim.qcow2’ saved [7425687552/7425687552]

**Comment by gabrik** [comment]
Hi,

Commit 0c1016b2456243cb523de6aac68ae06fa02cd929 should have fix this issue, please check

**Comment by gabrik** [comment]
Regarding slow migration due to disk copy this line of the KVMLibvirt plugin should be the cause of that beaviour 
https://github.com/atolab/fog05/blob/master/plugins/KVMLibvirt/KVMLibvirt_plugin.py#L667

The changes to make this works better should be to remove the `libvirt.VIR_MIGRATE_NON_SHARED_DISK` and use `migrate3 (libvirt_destconn, params, flags)` instead of `migrate(libvirt_destconn, flags, name, uri, bandwidth)

**Comment by gabrik** [comment]
Commit: 6ac72cca7056c8ee86bbb3bb6956ebb5dc30010c should have solved this
