### ISSUE TITLE
trying to install on ubuntu 18.04 to test LXD plugin, all is installed but "fos" command fails

### ISSUE THREAD

**Issue by bmullan** [atolab/fog05#14]
I am on any 18.04 host and installed from the source files per instructions.

$ **fos start -p ~/Downloads/fog05/plugins** 
 _____            ____   ____
|  ___|__   __ _ / __ \ | ___|
| |_ / _ \ / _` | | /| ||___ \ 
|  _| (_) | (_| | |/_| | ___) |
|_|  \___/ \__, |\____/ |____/ 
           |___/ 

##### OUTPUT TO LOGFILE #####

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.1.3-py3.6.egg/fog05/fosagent.py", line 60, in __init__
    self.dstore = Store(sid, self.droot, self.dhome, 1024)
  File "/usr/local/lib/python3.6/dist-packages/dstore-0.1.1-py3.6.egg/dstore/store.py", line 30, in __init__
    self.__controller = StoreController(self)
  File "/usr/local/lib/python3.6/dist-packages/dstore-0.1.1-py3.6.egg/dstore/controller.py", line 70, in __init__
    self.dds_controller = DDSController.controller()
  File "/usr/local/lib/python3.6/dist-packages/dstore-0.1.1-py3.6.egg/dstore/controller.py", line 58, in controller
    the_dds_controller = DDSController()
  File "/usr/local/lib/python3.6/dist-packages/dstore-0.1.1-py3.6.egg/dstore/controller.py", line 17, in __init__
    self.dds_runtime = Runtime.get_runtime()
  File "/usr/local/lib/python3.6/dist-packages/python_cdds-0.1.0-py3.6.egg/cdds/runtime.py", line 12, in get_runtime
    the_runtime = Runtime()
  File "/usr/local/lib/python3.6/dist-packages/python_cdds-0.1.0-py3.6.egg/cdds/runtime.py", line 20, in __init__
    self.ddslib = CDLL(cham_lib_path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /usr/local/lib/libddsc.so: cannot open shared object file: No such file or directory**

I can see the above error but I've tried googling to find "what" **libddsc or libddsc.so** comes from and so far haven't found anything?   Would you know what that is by chance that I'm missing?

I want to try this with the LXD plugin and my LXD 3.x containers.

thanks
brian

**Comment by bmullan** [comment]
I've moved beyond the above and 

$ fos start -p ~/plugins/

 _____            ____   ____
|  ___|__   __ _ / __ \ | ___|
| |_ / _ \ / _` | | /| ||___ \ 
|  _| (_) | (_| | |/_| | ___) |
|_|  \___/ \__, |\____/ |____/ 
           |___/ 

##### OUTPUT TO LOGFILE #####

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.1.3-py3.6.egg/fog05/fosagent.py", line 104, in __init__
    load_method(name, plugin_uuid)
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.1.3-py3.6.egg/fog05/fosagent.py", line 166, in __load_runtime_plugin
    rt = rt.run(agent=self, uuid=plugin_uuid, configuration=configuration)
  File "./ros2/__init__.py", line 11, in run
    from ros2_file import ROS2
**ModuleNotFoundError: No module named 'ros2_file'**

Any ideas?

**Comment by gabrik** [comment]
Hi @bmullan the libraries it is looking from comes from https://github.com/eclipse/cyclonedds
For the second error, you can remove from the pluging directory all the plugins that you don't need, becase in this version the agent is loading all the plugins that it can find in that directory, so in your case you need only: 

- linux
- brctl
- LXD

The otherones can be removed, also you need to install two python packages in order to support LXD
`pip3 install pylxd packaging`

Just last two comments we haven't yet tried with LXD 3.x, and the CLI interface is a going through a rewriting so may not work well, you can use the python API

**Comment by bmullan** [comment]
Thanks Gabriele.
I think I am now able to  start fog05.

Here is the fosagent_log.log contents:

$ more fosagent*.log
[2018-05-29 21:51:13,194] - [INFO] > < __init__() > FosAgent Starting...
[2018-05-29 21:51:13,194] - [INFO] > < __init__() > Plugins Dir: /home/bmullan/Downloads/fog05/plugins
[2018-05-29 21:51:13,195] - [INFO] > < __init__() > [ INIT ] Loading OS Plugin...
[2018-05-29 21:51:13,195] - [INFO] > < __init__() > fosAgent running on GNU\Linux
[2018-05-29 21:51:13,201] - [INFO] > < __init__() >  Hello from GNU\Linux Plugin
[2018-05-29 21:51:13,202] - [INFO] > < __init__() >  Running on ubuntu
[2018-05-29 21:51:13,202] - [INFO] > < __init__() >  Package manger apt loaded! 
[2018-05-29 21:51:13,217] - [INFO] > < __init__() > [ DONE ] Loading OS Plugin...
[2018-05-29 21:51:13,226] - [INFO] > < __init__() > [ INIT ] Creating Desired State Store ROOT: dfos://0 HOME: dfos://0/af83131176b84
a228b9ebebcb4422881
[2018-05-29 21:51:13,227] - [ERROR] > < __init__() > Something trouble happen /usr/local/lib/libddsc.so: cannot open shared object fi
le: No such file or directory 
[2018-05-29 22:45:30,717] - [INFO] > < __init__() > FosAgent Starting...
[2018-05-29 22:45:30,718] - [INFO] > < __init__() > Plugins Dir: /home/bmullan/Downloads/fog05/plugins
[2018-05-29 22:45:30,718] - [INFO] > < __init__() > [ INIT ] Loading OS Plugin...
[2018-05-29 22:45:30,718] - [INFO] > < __init__() > fosAgent running on GNU\Linux
[2018-05-29 22:45:30,721] - [INFO] > < __init__() >  Hello from GNU\Linux Plugin
[2018-05-29 22:45:30,721] - [INFO] > < __init__() >  Running on ubuntu
[2018-05-29 22:45:30,721] - [INFO] > < __init__() >  Package manger apt loaded! 
[2018-05-29 22:45:30,736] - [INFO] > < __init__() > [ DONE ] Loading OS Plugin...
[2018-05-29 22:45:30,745] - [INFO] > < __init__() > [ INIT ] Creating Desired State Store ROOT: dfos://0 HOME: dfos://0/af83131176b84
a228b9ebebcb4422881
[2018-05-29 22:45:31,253] - [INFO] > < __init__() > [ DONE ] Creating Desired State Store
[2018-05-29 22:45:31,253] - [INFO] > < __init__() > [ INIT ] Creating Actual State Store ROOT: afos://0 HOME: afos://0/af83131176b84a
228b9ebebcb4422881
[2018-05-29 22:45:31,757] - [INFO] > < __init__() > [ DONE ] Creating Actual State Store
[2018-05-29 22:45:31,757] - [INFO] > < __init__() > [ INIT ] Populating Actual Store with data from OS Plugin
[2018-05-29 22:45:31,796] - [INFO] > < __init__() > [ DONE ] Populating Actual Store with data from OS Plugin
[2018-05-29 22:45:31,796] - [INFO] > < __init__() > Autoloading plugins....
[2018-05-29 22:45:31,797] - [INFO] > < __load_runtime_plugin() > Loading a Runtime plugin: native
[2018-05-29 22:45:31,797] - [INFO] > < __load_runtime_plugin() > [ INIT ] Loading a Runtime plugin: native
[2018-05-29 22:45:31,801] - [INFO] > < __init__() >  Hello from Native Plugin
[2018-05-29 22:45:31,801] - [INFO] > < startRuntime() >  Native Plugin - Observing dfos://0/af83131176b84a228b9ebebcb4422881/runtime/
809839f2-b511-489d-a8cf-8c80d714893e/entity/*
[2018-05-29 22:45:31,806] - [INFO] > < __load_runtime_plugin() > [ DONE ] Loading a Runtime plugin: native
[2018-05-29 22:45:31,806] - [INFO] > < __load_runtime_plugin() > Loading a Runtime plugin: ros2
[2018-05-29 22:45:31,797] - [INFO] > < __load_runtime_plugin() > Loading a Runtime plugin: native
[2018-05-29 22:45:31,797] - [INFO] > < __load_runtime_plugin() > [ INIT ] Loading a Runtime plugin: native
[2018-05-29 22:45:31,801] - [INFO] > < __init__() >  Hello from Native Plugin
[2018-05-29 22:45:31,801] - [INFO] > < startRuntime() >  Native Plugin - Observing dfos://0/af83131176b84a228b9ebebcb4422881/runtime/
809839f2-b511-489d-a8cf-8c80d714893e/entity/*
[2018-05-29 22:45:31,806] - [INFO] > < __load_runtime_plugin() > [ DONE ] Loading a Runtime plugin: native
[2018-05-29 22:45:31,806] - [INFO] > < __load_runtime_plugin() > Loading a Runtime plugin: ros2
[2018-05-29 22:45:31,806] - [INFO] > < __load_runtime_plugin() > [ INIT ] Loading a Runtime plugin: ros2
[2018-05-29 22:45:31,808] - [ERROR] > < __init__() > Something trouble happen No module named 'ros2_file' 
[2018-05-30 09:35:11,186] - [INFO] > < __init__() > FosAgent Starting...
[2018-05-30 09:35:11,188] - [INFO] > < __init__() > Plugins Dir: ./plugins
[2018-05-30 09:35:11,188] - [INFO] > < __init__() > [ INIT ] Loading OS Plugin...
[2018-05-30 09:35:11,188] - [INFO] > < __init__() > fosAgent running on GNU\Linux
[2018-05-30 09:35:11,191] - [INFO] > < __init__() >  Hello from GNU\Linux Plugin
[2018-05-30 09:35:11,191] - [INFO] > < __init__() >  Running on ubuntu
[2018-05-30 09:35:11,191] - [INFO] > < __init__() >  Package manger apt loaded! 
[2018-05-30 09:35:19,655] - [INFO] > < __init__() > [ DONE ] Loading OS Plugin...
[2018-05-30 09:35:19,664] - [INFO] > < __init__() > [ INIT ] Creating Desired State Store ROOT: dfos://0 HOME: dfos://0/af83131176b84
a228b9ebebcb4422881
[2018-05-30 09:35:20,177] - [INFO] > < __init__() > [ DONE ] Creating Desired State Store
[2018-05-30 09:35:20,178] - [INFO] > < __init__() > [ INIT ] Creating Actual State Store ROOT: afos://0 HOME: afos://0/af83131176b84a
228b9ebebcb4422881
[2018-05-30 09:35:20,681] - [INFO] > < __init__() > [ DONE ] Creating Actual State Store
[2018-05-30 09:35:20,681] - [INFO] > < __init__() > [ INIT ] Populating Actual Store with data from OS Plugin
[2018-05-30 09:35:20,720] - [INFO] > < __init__() > [ DONE ] Populating Actual Store with data from OS Plugin
[2018-05-30 09:35:20,720] - [INFO] > < __init__() > Autoloading plugins....
[2018-05-30 09:35:20,720] - [INFO] > < __load_network_plugin() > Loading a Network plugin: brctl
[2018-05-30 09:35:20,720] - [INFO] > < __load_network_plugin() > [ INIT ] Loading a Network plugin: brctl
[2018-05-30 09:35:20,722] - [INFO] > < __init__() >  Hello from bridge-utils Plugin
[2018-05-30 09:35:20,722] - [INFO] > < startRuntime() >  bridge-utils Plugin - Observing dfos://0/af83131176b84a228b9ebebcb4422881/ne
twork/d42b4163-af35-423a-acb4-a228290cf0be/networks/*
[2018-05-30 09:35:20,727] - [INFO] > < __load_network_plugin() > [ DONE ] Loading a Network plugin: brctl
[2018-05-30 09:35:20,727] - [INFO] > < run() > fosAgent Observing for onboarding on: dfos://0/af83131176b84a228b9ebebcb4422881/onboar
d/*
[2018-05-30 09:35:20,727] - [INFO] > < run() > fosAgent Observing plugins on: dfos://0/af83131176b84a228b9ebebcb4422881/plugins
[2018-05-30 09:35:20,727] - [INFO] > < run() > [ DONE ] fosAgent Up and Running

**Comment by gabrik** [comment]
Ok, it is started but I don't see any loading on the LXD plugin, do you have pull the last version?
