### ISSUE TITLE
Run-time error on Nvidia Jetson TX2 - list index out of range

### ISSUE THREAD

**Issue by giovanni-rigazzi** [atolab/fog05#18]
An error occurs when running fos start on an Nvidia Jetson TX2 (kernel 4.4.38-tegra): 

[2018-07-16 15:27:40,215] - [INFO] > < __init__() > FosAgent Starting...
[2018-07-16 15:27:40,215] - [INFO] > < __init__() > Plugins Dir: ./plugins/
[2018-07-16 15:27:40,216] - [INFO] > < __init__() > [ INIT ] Loading OS Plugin...
[2018-07-16 15:27:40,216] - [INFO] > < __init__() > fosAgent running on GNU\Linux
[2018-07-16 15:27:40,222] - [INFO] > < __init__() >  Hello from GNU\Linux Plugin
[2018-07-16 15:27:40,222] - [INFO] > < __init__() >  Running on ubuntu
[2018-07-16 15:27:40,223] - [INFO] > < __init__() >  Package manger apt loaded! 
[2018-07-16 15:27:40,254] - [INFO] > < __init__() > [ DONE ] Loading OS Plugin...
[2018-07-16 15:27:40,271] - [INFO] > < __init__() > [ INIT ] Creating Desired State Store ROOT: dfos://0 HOME: dfos://0/ae15719763c84b35196c20a95728b806
[2018-07-16 15:27:40,794] - [INFO] > < __init__() > [ DONE ] Creating Desired State Store
[2018-07-16 15:27:40,796] - [INFO] > < __init__() > [ INIT ] Creating Actual State Store ROOT: afos://0 HOME: afos://0/ae15719763c84b35196c20a95728b806
[2018-07-16 15:27:41,354] - [INFO] > < __init__() > [ DONE ] Creating Actual State Store
[2018-07-16 15:27:41,357] - [INFO] > < __init__() > [ INIT ] Populating Actual Store with data from OS Plugin
[2018-07-16 15:27:41,460] - [ERROR] > < __init__() > Something trouble happen list index out of range 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fog05-0.1.3-py3.5.egg/fog05/fosagent.py", line 85, in __init__
    self.__populate_node_information()
  File "/usr/local/lib/python3.5/dist-packages/fog05-0.1.3-py3.5.egg/fog05/fosagent.py", line 238, in __populate_node_information
    node_info.update({'cpu': self.__osPlugin.get_processor_information()})
  File "/home/nvidia/src/fog05/plugins/linux/linux_plugin.py", line 198, in get_processor_information
    frequency = frequency[i][2]
IndexError: list index out of range

**Comment by gabrik** [comment]
Thanks @giovanni-rigazzi 

I found that the bug is coming from psutil that retunts inconsistent information about the number of CPU in the Jetson TX2

```
nvidia@tegra-ubuntu:~/src/fog05$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> frequency = psutil.cpu_freq(percpu=True)
>>> frequency
[scpufreq(current=345.6, min=345.6, max=2035.2), scpufreq(current=345.6, min=345.6, max=2035.2)]
>>> psutil.cpu_count()
4
>>> len(frequency)
2
>>> 
```
I will use`min( psutil.cpu_count(),len(psutil.cpu_freq(percpu=True)))` to get the number of CPU as this should be the correct one

**Comment by gabrik** [comment]
Commit 6a289ff17a655552b74b322e70d9fcaed121ede1 fixes this issue
