### ISSUE TITLE
Error in loading KVM plugin on Ubuntu 14.04 (Python 3.4)

### ISSUE THREAD

**Issue by giovanni-rigazzi** [atolab/fog05#8]
An error is thrown when a KVM plugin is being loaded: 

- [INFO] > < __react_to_plugins() >  Received a plugin action on Desired Store URI: dfos://0/94fa5cf7c0ea32de2352ae595a0590e0/plugins Value: {"plugins": [{"version": 1, "status": "add", "uuid": "8fb33188-846c-45f8-83df-2a25e6b78049", "requirements": ["libvirt-python", "jinja2"], "type": "runtime", "name": "KVMLibvirt"}]} Version: 3
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/lib/python3.4/dist-packages/python_cdds-0.1.0-py3.4.egg/cdds/reader.py", line 13, in trampoline_on_data_available
  File "/usr/local/lib/python3.4/dist-packages/python_cdds-0.1.0-py3.4.egg/cdds/runtime.py", line 193, in dispatch_data_listener
  File "/usr/local/lib/python3.4/dist-packages/python_cdds-0.1.0-py3.4.egg/cdds/reader.py", line 96, in __handle_data
  File "/usr/local/lib/python3.4/dist-packages/dstore-0.1.0-py3.4.egg/dstore/controller.py", line 245, in handle_remote_put
  File "/usr/local/lib/python3.4/dist-packages/dstore-0.1.0-py3.4.egg/dstore/store.py", line 134, in notify_observers
  File "/usr/local/lib/python3.4/dist-packages/fog05-0.1.3-py3.4.egg/fog05/fosagent.py", line 234, in __react_to_plugins
    self.pl.install_requirements(req)
  File "/usr/local/lib/python3.4/dist-packages/fog05-0.1.3-py3.4.egg/fog05/PluginLoader.py", line 46, in install_requirements
    pip.main(pip_args)
AttributeError: 'module' object has no attribute 'main'

**Comment by giovanni-rigazzi** [comment]
As a workaround, downgrading pip to 9.0.1  solves the issue.

**Comment by gabrik** [comment]
Seems incopatibility whit Pip version 10.0.0b2, will investigate
